version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: stake_event_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: indexer
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: event_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
